// Copyright (c) 2025-2026 natusor (MONEU)
// Distributed under the MIT software license, see the accompanying
// file COPYING or http://www.opensource.org/licenses/mit-license.php.

#ifndef MONEU_CHAINPARAMSSEEDS_H
#define MONEU_CHAINPARAMSSEEDS_H
// GENERATED by contrib/generate-seeds.py. Do not edit by hand.
// Edit contrib/seeds_main.txt and run the script.
#include <cstdint>
#include <cstddef>
namespace NetParams {
static const uint8_t MAINNET_SEED_DATA[] = {
    0x01,0x04,0x87,0xb5,0xff,0xdb,0x20,0x87,
};
static const size_t MAINNET_SEED_DATA_SIZE =
    sizeof(MAINNET_SEED_DATA);
} // namespace NetParams
#endif
