#!/usr/bin/env python3
"""Turn a list of node addresses into a compiled seed table.

Reads plain text with one address per line and writes a C++ header holding
the same addresses in a compact binary form. Modelled on Bitcoin's
contrib/seeds/generate-seeds.py and using the same encoding.

Why a binary table rather than a list of strings.

A node that knows nobody has to start somewhere and the list of starting
points is compiled into the binary so that it works before any file has
been read and before any name has been resolved. Strings would do that too
but they cost about three times the space and have to be parsed at start-up
and cannot hold an onion address at all. The binary form takes an IPv4
address in eight bytes and leaves room for networks that have no textual
form worth parsing.

Usage:
    generate-seeds.py seeds_main.txt > src/chainparamsseeds.h

Input format, one per line, with # for comments:
    135.181.255.219:8327
    [2a02:8108:94a1:9400::1]:8327
"""

import re
import struct
import sys


# Network identifiers, the same numbering as BIP155 so a MONEU (blockchain)
# seed table and a Bitcoin one can be read by the same eyes. Only the first
# two are in use here. The rest are listed so that adding them later does
# not renumber anything already written.
NET_IPV4 = 1
NET_IPV6 = 2
NET_TORV3 = 4
NET_I2P = 5
NET_CJDNS = 6

DEFAULT_PORT = 8327


def parse_ipv4(host):
    """Four octets, or None if this is not a dotted quad."""
    parts = host.split('.')
    if len(parts) != 4:
        return None
    out = []
    for p in parts:
        if not p.isdigit():
            return None
        v = int(p)
        if v < 0 or v > 255:
            return None
        out.append(v)
    return bytes(out)


def parse_ipv6(host):
    """Sixteen bytes, or None. Handles the double colon shorthand."""
    if '.' in host:
        return None
    if host.count('::') > 1:
        return None

    if '::' in host:
        left, right = host.split('::')
        lg = [g for g in left.split(':') if g]
        rg = [g for g in right.split(':') if g]
        if len(lg) + len(rg) > 7:
            return None
        groups = lg + ['0'] * (8 - len(lg) - len(rg)) + rg
    else:
        groups = host.split(':')
        if len(groups) != 8:
            return None

    out = b''
    for g in groups:
        if not g:
            g = '0'
        if len(g) > 4:
            return None
        try:
            v = int(g, 16)
        except ValueError:
            return None
        out += struct.pack('>H', v)
    return out


def parse_line(line):
    """One address line to (network, address bytes, port), or None."""
    comment = line.find('#')
    if comment != -1:
        line = line[:comment]
    line = line.strip()
    if not line:
        return None

    port = DEFAULT_PORT

    # Bracketed form for IPv6, because a bare IPv6 address is full of the
    # colon that otherwise separates the port.
    m = re.match(r'^\[([0-9a-fA-F:]+)\](?::(\d+))?$', line)
    if m:
        host = m.group(1)
        if m.group(2):
            port = int(m.group(2))
        addr = parse_ipv6(host)
        if addr is None:
            sys.stderr.write('skipping malformed IPv6: %s\n' % line)
            return None
        return (NET_IPV6, addr, port)

    # Otherwise the last colon separates the port, if there is one.
    host = line
    if line.count(':') == 1:
        host, portstr = line.rsplit(':', 1)
        if portstr.isdigit():
            port = int(portstr)
        else:
            host = line

    addr = parse_ipv4(host)
    if addr is not None:
        return (NET_IPV4, addr, port)

    addr = parse_ipv6(host)
    if addr is not None:
        return (NET_IPV6, addr, port)

    sys.stderr.write('skipping unrecognised address: %s\n' % line)
    return None


def serialise(entry):
    """One entry as network byte, length, address, then port big-endian."""
    network, addr, port = entry
    out = struct.pack('B', network)
    out += struct.pack('B', len(addr))     # never exceeds 16 so one byte
    out += addr
    out += struct.pack('>H', port)
    return out


def main():
    if len(sys.argv) != 2:
        sys.stderr.write(__doc__)
        return 1

    entries = []
    with open(sys.argv[1]) as f:
        for line in f:
            e = parse_line(line)
            if e is not None:
                entries.append(e)

    if not entries:
        sys.stderr.write('no usable addresses found\n')
        return 1

    blob = b''
    for e in entries:
        blob += serialise(e)

    out = sys.stdout
    out.write('#ifndef MONEU_CHAINPARAMSSEEDS_H\n')
    out.write('#define MONEU_CHAINPARAMSSEEDS_H\n')
    out.write('\n')
    out.write('// Fixed seed nodes for the MONEU (blockchain) network.\n')
    out.write('//\n')
    out.write('// GENERATED by contrib/generate-seeds.py. Do not edit by\n')
    out.write('// hand. Edit contrib/seeds_main.txt and run the script.\n')
    out.write('//\n')
    out.write('// Each entry is a network identifier byte then a length\n')
    out.write('// byte then the address then the port big-endian. Network 1\n')
    out.write('// is IPv4 and 2 is IPv6, numbered as in BIP155 so the table\n')
    out.write('// can grow to onion addresses without renumbering.\n')
    out.write('//\n')
    out.write('// A seed is a meeting point and nothing more. It has no say\n')
    out.write('// in the rules and an attacker who replaced every entry here\n')
    out.write('// still could not make a valid block, because validity comes\n')
    out.write('// from proof of work and from nothing a seed can offer.\n')
    out.write('\n')
    out.write('#include <cstdint>\n')
    out.write('#include <cstddef>\n')
    out.write('\n')
    out.write('namespace NetParams {\n')
    out.write('\n')
    out.write('static const uint8_t MAINNET_SEED_DATA[] = {\n')
    for i in range(0, len(blob), 8):
        chunk = blob[i:i + 8]
        out.write('    ' + ','.join('0x%02x' % b for b in chunk) + ',\n')
    out.write('};\n')
    out.write('\n')
    out.write('static const size_t MAINNET_SEED_DATA_SIZE =\n')
    out.write('    sizeof(MAINNET_SEED_DATA);\n')
    out.write('\n')
    out.write('} // namespace NetParams\n')
    out.write('\n')
    out.write('#endif\n')

    sys.stderr.write('wrote %d seed(s), %d bytes\n' % (len(entries), len(blob)))
    return 0


if __name__ == '__main__':
    sys.exit(main())
